### ISSUE TITLE
Unable to set showcase to false

### ISSUE THREAD

**Issue by drubin** [yannh/terraform-provider-statuspage#11]
Using the provider we are unable to set `showcase = false` no matter what the sate was. Setting it to true however does update the sate. 

So the following transition does not seem to work 

`showcase = true -> showcase = false`

but the following does work 

`showcase = false -> showcase = true`

I think this has to do with the `omitempty` on boolean fields, as I see the same issue for `only_show_if_degraded`

Haven't been able to test if removing `omitempty` fixes the issue though.

**Comment by yannh** [comment]
Hi drubin! Yes that's probably what it is. I initially set omitempty so the provider would rely on the defaults of statuspage when a variable is not set - but false counts as empty. This could probably be rewritten using pointers... I ll try to when I find some time!

**Comment by drubin** [comment]
I can try a patch removing the omitempty? 

It seems like unless Golang's definition of empty matches your API's it might be better to set the default value to the Api default.
https://www.sohamkamani.com/blog/golang/2018-07-19-golang-omitempty/

**Comment by yannh** [comment]
I had a look at this, there are really two approaches. One is to only use pointers for all the resource fields in the SDK - keeping omitempty, we would not have the problem of bools set to false or strings set to ""  not being marshalled anymore.. This seems to be how the AWS SDK, or the Azure SDK, are written?

Another would be to remove the omitempty, and set a default value in the Terraform plugin that match the default value from the Statuspage documentation. Since some fields were underdocumented, that seemed not that easy to do. But maybe it is better to rely on a fixed behaviour in the Terraform plugin.

I'll think about this a bit more...

**Comment by yannh** [comment]
I just had a chat with a colleague about this, we agreed pointers was the way to go! I'll try to submit a patch soon.

**Comment by yannh** [comment]
Done! Test & acceptance tests pass, though I would need to add more to cover this specific use case.

**Comment by yannh** [comment]
Merged additional tests https://github.com/yannh/terraform-provider-statuspage/pull/17
Note that I need to find a way to run tests in a branch without risking exposing the tokens used in CI - the test do pass though.

**Comment by drubin** [comment]
Thanks! Will give it a try when I can
