### ISSUE TITLE
Switch to MIT License

### ISSUE THREAD

**Issue by dthagard** [yannh/terraform-provider-statuspage#6]
Any chance that you would consider switching to the MIT license for this repo?

**Comment by yannh** [comment]
Hi @dthagard ! I chose the MPL license for compatibility with Terraform,  because it is the license used by many other Terraform plugins, and because I "like the license". I am not sure how a MIT license would help though - since Terraform itself is licensed under MPL? 
I would love to hear about your specific use-case. Feel free to get in touch by email - maybe we can sort something out.
